### ISSUE TITLE
Better implementation for 16ukerk

### ISSUE THREAD

**Issue by Autom3** [nerdland-unofficial-fans/nerdlandbot#106]
- Should it be limited to only the lounge?
- The while loop implementation should be changed to a Scheduler which triggers a function at 16:00 to check if anyone needs to be notified
- Translations

Previous PR: https://github.com/nerdland-unofficial-fans/nerdlandbot/pull/105

**Comment by Eva774** [comment]
To add to this: 

- Change the message to "het is 16u" instead of "het is 4u" since the command is named 16ukerk and consistency is nice.
- Limit the messages that are send as a reaction to #botplayground to avoid clutter and annoyance?
- If the command is limited to certain channels: identify them by ID and not by name and add them to the guildconfig so that they are configurable without changing the code.
